spring.application.name=saij-knowledge-graph-api

app.graph.domain=https://saij-knowledge-graph-api.com/concepts/
app.graph.saij-base=http://vocabularios.saij.gob.ar/saij/xml.php?skosTema=
app.graph.data-path=data-storage/legal_graph_tdb
app.graph.initial-file=classpath:saij-skos-20240603.xml